name = "QBase"
uuid = "e52e8ede-12bf-4731-8af7-b01f6064cb11"
authors = ["Brian Doolittle <brian.d.doolittle@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RandomMatrices = "2576dda1-a324-5b11-aa66-c48ed7e3c618"

[compat]
Combinatorics = "1.0"
RandomMatrices = "0.5"
julia = "1.4"
